version: 2.1

orbs:
 android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - android/restore-build-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies      
      - android/save-build-cache
      - run:
          command: ./gradlew lint test

workflows:
  build:
    jobs:
      - build 