version: 2.1

orbs:
 android: circleci/android@0.2.0

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - restore-build-cache
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies      
      - run:
          command: ./gradlew lint test
      - save-build-cache

workflows:
  build:
    jobs:
      - build 